### ISSUE TITLE
[EPIC] Новый тип диагностик "Security Hotspot"

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#640]
Необходимо реализовать новый тип диагностик "Security Hotspot".

Ссылка на источник в сонаре: https://docs.sonarqube.org/latest/user-guide/security-hotspots/

- [x] Добавить новый тип #684
- [x] Доработать документацию (надо четко понимать, когда что выбирать) #684
- [x] Доработать шаблоны GH #684
- [x] Доработать плагин сонара https://github.com/1c-syntax/sonar-bsl-plugin-community/issues/65
- [x] Доработать плагин VSC (для него аналогично уязвимости) https://github.com/1c-syntax/vsc-language-1c-bsl/issues/169 
- [x] Уведомить Капралова Александра, чтобы он учел в EDT

**Comment by nixel2007** [comment]
кажется, это эпик и его надо разбивать на ишузы :)

**Comment by theshadowco** [comment]
а здесь есть такая сущность или просто таски связать между собой?

**Comment by nixel2007** [comment]
Тут вроде нет :(

**Comment by asosnoviy** [comment]
> Доработать плагин VSC (для него аналогично уязвимости)

Кажется это происходит на стороне сервера
